["foo:bar"]
description = "This is foo:bar."
run = "#!/usr/bin/env sh\n\nset -- \"$PWD\" \"$@\"\ncd \"$MISE_PROJECT_ROOT\"/\"./mise-sh-tasks/\"\n. \"test.lib.sh\"\ncd \"$1\"\nshift\n\"task_foo__bar\" \"$@\""
["foo:bar".tools]
jq = "latest"

["bar:baz"]
description = "This is bar:baz."
run = "#!/usr/bin/env sh\n\nset -- \"$PWD\" \"$@\"\ncd \"$MISE_PROJECT_ROOT\"/\"./mise-sh-tasks/\"\n. \"test.lib.sh\"\ncd \"$1\"\nshift\n\"task_bar__baz\" \"$@\""
