name: Tests
on:
  push:
    branches:
      - main
jobs:
  test-unixy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Uname
        run: uname -a
      - name: Environment Variables
        run: env
      - name: Bash Version
        run: bash --version
      - name: Run Test
        run: ./task --verbose test
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Enable Symlinks
        run: git config --global core.symlinks true
      - uses: actions/checkout@v4
      - name: System Info
        run: systeminfo
      - name: Environment Variables
        run: set
        shell: cmd
      - name: Cache BusyBox
        # actions/cache: Cache dependencies and build outputs in GitHub Actions https://github.com/actions/cache
        uses: actions/cache@v4
        with:
          # “Please note that Windows environment variables (like %LocalAppData%) will NOT be expanded by this action. Instead, prefer using ~ in your paths which will expand to the HOME directory.”
          path: ~\.cache\task-sh
          key: busybox-${{ runner.os }}-${{ hashFiles('task.cmd') }}
          restore-keys: |
            busybox-${{ runner.os }}-
      - name: Load BusyBox
        run: .\task.cmd nop
      - name: Run Test
        run: .\task.cmd --verbose test
